export const TypesStore = {
  state: {
    //global cambia de acuerdo al contexto
    LANGUAGE: `GLOBAL:LANGUAGE`,
    STUDENTS: `GLOBAL:STUDENTS`,
    PSTUDENTS: `GLOBAL:PSTUDENTS`
  },
  actions: {
    GET_STUDENTS: `GLOBAL:GET_STUDENTS`,
    POST_STUDENTS: `GLOBAL:POST_STUDENTS`,
    DEL_STUDENTS: `GLOBAL:DEL_STUDENTS`,
    PUST_STUDENTS: `GLOBAL:PUST_STUDENTS`,
  },
  mutations: {
    SET_LANGUAGE: `GLOBAL:SET_LANGUAGE`,
    SET_STUDENTS: `GLOBAL:GET_STUDENTS`,
    SETT_STUDENTS: `GLOBAL:POST_STUDENTS`,
    DELSET_STUDENTS: `GLOBAL:DEL_STUDENTS`,
    PUTSET_STUDENTS: `GLOBAL:PUST_STUDENTS`,
  }
};
